on:
    workflow_dispatch:
    push:
       branches:
         - main

name: Quarto Render

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
    
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
    
      - name: Install R
        uses: r-lib/actions/setup-r@v2
    
      - name: Session info
        run: Rscript -e 'sessionInfo()'
    
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2 # update
    
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
    
      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2 # update
    
      #- name: Install remote packages
      #  run: |
      #   Rscript -e 'remotes::install_github("DevPsyLab/petersenlab")'

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
      
      - name: Commit to GitHub
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add . -f
          git commit -m 'Re-build wiki' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
